### ISSUE TITLE
有点不对，8bits要通过16bits转换，这转换期间的显存和16bit要的一样，22g的显存玩不了。

### ISSUE THREAD

**Issue by zengzikang** [baichuan-inc/Baichuan2#106]
如题，想用8bits，但是用不了，用4bits，报错ImportError: cannot import name 'AutoModelForCausalLM' from 'transformers'

**Comment by jameswu2014** [comment]
16bits转8bits可以通过cpu转，转完后再放到gpu上的。

**Comment by zengzikang** [comment]
能不能出个8bits的模型？cpu转，我刚好是32G的内存，也不够用。
