### ISSUE TITLE
lora微调后推理速度好慢,  而且loss 不收敛

### ISSUE THREAD

**Issue by 631068264** [baichuan-inc/Baichuan2#112]
ds_config.json

```json
{
  "train_micro_batch_size_per_gpu": "auto",
  "gradient_accumulation_steps": "auto",
  "gradient_clipping": "auto",
  "zero_allow_untested_optimizer": true,
  "fp16": {
    "enabled": "auto",
    "loss_scale": 0,
    "initial_scale_power": 16,
    "loss_scale_window": 1000,
    "hysteresis": 2,
    "min_loss_scale": 1
  },
  "zero_optimization": {
    "stage": 2,
    "allgather_partitions": true,
    "allgather_bucket_size": 5e8,
    "reduce_scatter": true,
    "reduce_bucket_size": 5e8,
    "overlap_comm": false,
    "contiguous_gradients": true
  },
  "csv_monitor": {
    "enabled": false,
    "output_path": "output/ds_logs/",
    "job_name": "train_bert"
}
}
```

微调脚本
```
export CUDA_LAUNCH_BLOCKING=1
export CUDA_VISIBLE_DEVICES=0

hostfile=""
deepspeed --hostfile=$hostfile fine-tune.py  \
    --report_to "none" \
    --data_path "data/belle_chat_ramdon_10k.json" \
    --model_name_or_path "baichuan-inc/Baichuan2-13B-Chat" \
    --output_dir "output" \
    --model_max_length 512 \
    --num_train_epochs 4 \
    --per_device_train_batch_size 16 \
    --gradient_accumulation_steps 1 \
    --save_strategy epoch \
    --learning_rate 2e-5 \
    --lr_scheduler_type constant \
    --adam_beta1 0.9 \
    --adam_beta2 0.98 \
    --adam_epsilon 1e-8 \
    --max_grad_norm 1.0 \
    --weight_decay 1e-4 \
    --warmup_ratio 0.0 \
    --gradient_checkpointing True \
    --deepspeed ds_config.json \
    --logging_steps 1 \
    --save_steps 500 \
    --use_lora True \
    --bf16 True \
    --tf32 True
```

加载lora， 修改了web_demo.py

```python
model_id = 'baichuan-inc/Baichuan2-13B-Chat'
lora_path = 'fine-tune/output/checkpoint-2500'

@st.cache_resource
def init_model():
    from peft import AutoPeftModelForCausalLM
    model = AutoPeftModelForCausalLM.from_pretrained(lora_path, trust_remote_code=True)

    model.generation_config = GenerationConfig.from_pretrained(
        model_id
    )
    tokenizer = AutoTokenizer.from_pretrained(
        model_id,
        use_fast=False,
        trust_remote_code=True
    )
    return model, tokenizer
```

loss  从2.5 到2.1~1.7左右徘徊

80G显卡，用13B-Chat 微调，13B-Chat推理速度正常，用lora后 几乎4,5秒一个字弹出来。

**Comment by 631068264** [comment]
排查后发现lora用的CPU推理，加载Lora模型得指定device
```
    from peft import AutoPeftModelForCausalLM
    model = AutoPeftModelForCausalLM.from_pretrained(lora_path, trust_remote_code=True)
    model = model.cuda()
```

**Comment by 779257747** [comment]
想问您一下，您用的这套lora的基础代码是llama-efficient-tuning吗

**Comment by 779257747** [comment]
我在80G显卡，用13b-chat微调时，loss一直波动，之后就变为0了。

**Comment by 631068264** [comment]
> 想问您一下，您用的这套lora的基础代码是llama-efficient-tuning吗

不是啊 ，用的就是这个仓库例子

**Comment by wjh177** [comment]
你好，我想咨询一下，你在微调过程中消耗的显存大概是多少呢

**Comment by cuisws** [comment]
你好，我微调后的模型文件路径为下图，加载模型应该是checkpoint还是output，如果继续训练呢
![image](https://github.com/baichuan-inc/Baichuan2/assets/119495121/84f29c8b-20f0-49b7-803b-a4fc8b649145)

**Comment by tkone2018** [comment]
Traceback (most recent call last):
  File "/root/autodl-tmp/Baichuan2-main/lora_load.py", line 16, in <module>
    model = AutoPeftModelForCausalLM.from_pretrained(lora_path, trust_remote_code=True)
  File "/root/miniconda3/lib/python3.10/site-packages/peft/auto.py", line 101, in from_pretrained
    base_model = target_class.from_pretrained(base_model_path, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 494, in from_pretrained
    resolved_config_file = cached_file(
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/utils/hub.py", line 429, in cached_file
    resolved_file = hf_hub_download(
  File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '../Ba.
root@autodl-container-cc3746a64c-57e50a78:~/autodl-tmp/Baichuan2-main# 
，我按照你写的，报这个错

**Comment by tkone2018** [comment]
我训练的时候是根据base去训练的，不是chat

**Comment by xiaokuixk** [comment]
> Traceback (most recent call last): File "/root/autodl-tmp/Baichuan2-main/lora_load.py", line 16, in model = AutoPeftModelForCausalLM.from_pretrained(lora_path, trust_remote_code=True) File "/root/miniconda3/lib/python3.10/site-packages/peft/auto.py", line 101, in from_pretrained base_model = target_class.from_pretrained(base_model_path, **kwargs) File "/root/miniconda3/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 494, in from_pretrained resolved_config_file = cached_file( File "/root/miniconda3/lib/python3.10/site-packages/transformers/utils/hub.py", line 429, in cached_file resolved_file = hf_hub_download( File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn validate_repo_id(arg_value) File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id raise HFValidationError( huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '../Ba. root@autodl-container-cc3746a64c-57e50a78:~/autodl-tmp/Baichuan2-main# ，我按照你写的，报这个错

您好，请问这个问题你解决了吗？我也遇到了同样的问题。
