### ISSUE TITLE
Why are so many differences between `Baichuan2-13B-Chat` and `Baichuan2-7B-Chat` in `modeling_baichuan.py `?

### ISSUE THREAD

**Issue by gavin1332** [baichuan-inc/Baichuan2#114]
Are they compatible without regart to the hyperparameters?

**Comment by gavin1332** [comment]
And there are also slight differences between `Baichuan2-7B-Base` and `Baichuan2-7B-Chat`

**Comment by jameswu2014** [comment]
The are different.13B use alibi-mask for position-embedding while RoPE for 7B

**Comment by gavin1332** [comment]
Thanks. And How about the difference between `Baichuan2-7B-Base` and `Baichuan2-7B-Chat`, is there a bug fix or something else?

**Comment by Daya-Jin** [comment]
> Thanks. And How about the difference between `Baichuan2-7B-Base` and `Baichuan2-7B-Chat`, is there a bug fix or something else?

same question

**Comment by jameswu2014** [comment]
> Thanks. And How about the difference between `Baichuan2-7B-Base` and `Baichuan2-7B-Chat`, is there a bug fix or something else?

yes.
