### ISSUE TITLE
能否提供4-bit离线量化方法和保存4-bit模型的方法？

### ISSUE THREAD

**Issue by pipixia244** [baichuan-inc/Baichuan2#127]
bitsandbytes没有实现4-bit模型的保存，但项目提供了baichuan2的4bit量化版本模型，想问一下是怎么量化4-bit并保存的呢？

**Comment by jameswu2014** [comment]
在线量化后，把4bit相关的权重保存下来即可，不要用save_pretrained,

**Comment by menginbaidu** [comment]
> 在线量化后，把4bit相关的权重保存下来即可，不要用save_pretrained,

请问那用什么方式存

**Comment by xd-Nanan** [comment]
> > 在线量化后，把4bit相关的权重保存下来即可，不要用save_pretrained,
> 
> 请问那用什么方式存

同问。而且按照github上给出的离线量化方式，对baichuan2-13b-chat使用“load_in_8bit=True”方法进行离线8bits量化后，保存的权重文件会比原baichuan2-13b-chat还要大，有6个bin文件，占用显存肯定也是加倍了，不知道为什么会这样。。。。

**Comment by menginbaidu** [comment]
> > > 在线量化后，把4bit相关的权重保存下来即可，不要用save_pretrained,
> > 
> > 
> > 请问那用什么方式存
> 
> 同问。而且按照github上给出的离线量化方式，对baichuan2-13b-chat使用“load_in_8bit=True”方法进行离线8bits量化后，保存的权重文件会比原baichuan2-13b-chat还要大，有6个bin文件，占用显存肯定也是加倍了，不知道为什么会这样。。。。

我也这样，而且速度更慢了，很奇怪

**Comment by pipixia244** [comment]
> 在线量化后，把4bit相关的权重保存下来即可，不要用save_pretrained,

我试了用torch.save直接把state_dict保存，但这样用from_pretrained载入会报错（layer各个维度大小不一致），或者在推理的时候报错（mat1 mat2维度大小不一致）
想问一下baichuan2的4bit是怎么保存量化model的呢？

**Comment by jameswu2014** [comment]
> > > 在线量化后，把4bit相关的权重保存下来即可，不要用save_pretrained,
> > 
> > 
> > 请问那用什么方式存
> 
> 同问。而且按照github上给出的离线量化方式，对baichuan2-13b-chat使用“load_in_8bit=True”方法进行离线8bits量化后，保存的权重文件会比原baichuan2-13b-chat还要大，有6个bin文件，占用显存肯定也是加倍了，不知道为什么会这样。。。。

之前我也碰到过，是因为transformers库版本的问题。

**Comment by jameswu2014** [comment]
> > 在线量化后，把4bit相关的权重保存下来即可，不要用save_pretrained,
> 
> 我试了用torch.save直接把state_dict保存，但这样用from_pretrained载入会报错（layer各个维度大小不一致），或者在推理的时候报错（mat1 mat2维度大小不一致） 想问一下baichuan2的4bit是怎么保存量化model的呢？

保存4bit这部分是我们单独实现的，这部分代码我们没有开放出来。

**Comment by ACXuLiu** [comment]
> > 在线量化后，把4bit相关的权重保存下来即可，不要用save_pretrained,
> 
> 我试了用torch.save直接把state_dict保存，但这样用from_pretrained载入会报错（layer各个维度大小不一致），或者在推理的时候报错（mat1 mat2维度大小不一致） 想问一下baichuan2的4bit是怎么保存量化model的呢？

请问大佬解决这个问题了吗

**Comment by pipixia244** [comment]
> > > 在线量化后，把4bit相关的权重保存下来即可，不要用save_pretrained,
> > 
> > 
> > 我试了用torch.save直接把state_dict保存，但这样用from_pretrained载入会报错（layer各个维度大小不一致），或者在推理的时候报错（mat1 mat2维度大小不一致） 想问一下baichuan2的4bit是怎么保存量化model的呢？
> 
> 请问大佬解决这个问题了吗

改用[AutoGPTQ](https://github.com/PanQiWei/AutoGPTQ)了

**Comment by ACXuLiu** [comment]
> > > > 在线量化后，把4bit相关的权重保存下来即可，不要用save_pretrained,
> > > 
> > > 
> > > 我试了用torch.save直接把state_dict保存，但这样用from_pretrained载入会报错（layer各个维度大小不一致），或者在推理的时候报错（mat1 mat2维度大小不一致） 想问一下baichuan2的4bit是怎么保存量化model的呢？
> > 
> > 
> > 请问大佬解决这个问题了吗
> 
> 改用[AutoGPTQ](https://github.com/PanQiWei/AutoGPTQ)了

respect，但AutoGPTQ貌似并未继承Baichuan 🙇‍♂

**Comment by pipixia244** [comment]
> > > > > 在线量化后，把4bit相关的权重保存下来即可，不要用save_pretrained,
> > > > 
> > > > 
> > > > 我试了用torch.save直接把state_dict保存，但这样用from_pretrained载入会报错（layer各个维度大小不一致），或者在推理的时候报错（mat1 mat2维度大小不一致） 想问一下baichuan2的4bit是怎么保存量化model的呢？
> > > 
> > > 
> > > 请问大佬解决这个问题了吗
> > 
> > 
> > 改用[AutoGPTQ](https://github.com/PanQiWei/AutoGPTQ)了
> 
> respect，但AutoGPTQ貌似并未继承Baichuan 🙇‍♂

https://github.com/PanQiWei/AutoGPTQ/pull/164
https://github.com/PanQiWei/AutoGPTQ/blob/ac23d6b8193fa956a717931c8cc100defd780034/auto_gptq/modeling/_const.py#L21

**Comment by ACXuLiu** [comment]
> > > > > > 在线量化后，把4bit相关的权重保存下来即可，不要用save_pretrained,
> > > > > 
> > > > > 
> > > > > 我试了用torch.save直接把state_dict保存，但这样用from_pretrained载入会报错（layer各个维度大小不一致），或者在推理的时候报错（mat1 mat2维度大小不一致） 想问一下baichuan2的4bit是怎么保存量化model的呢？
> > > > 
> > > > 
> > > > 请问大佬解决这个问题了吗
> > > 
> > > 
> > > 改用[AutoGPTQ](https://github.com/PanQiWei/AutoGPTQ)了
> > 
> > 
> > respect，但AutoGPTQ貌似并未继承Baichuan 🙇‍♂
> 
> [PanQiWei/AutoGPTQ#164](https://github.com/PanQiWei/AutoGPTQ/pull/164) https://github.com/PanQiWei/AutoGPTQ/blob/ac23d6b8193fa956a717931c8cc100defd780034/auto_gptq/modeling/_const.py#L21

感谢～

**Comment by yijinsheng** [comment]
> > > > 在线量化后，把4bit相关的权重保存下来即可，不要用save_pretrained,
> > > 
> > > 
> > > 我试了用torch.save直接把state_dict保存，但这样用from_pretrained载入会报错（layer各个维度大小不一致），或者在推理的时候报错（mat1 mat2维度大小不一致） 想问一下baichuan2的4bit是怎么保存量化model的呢？
> > 
> > 
> > 请问大佬解决这个问题了吗
> 
> 改用[AutoGPTQ](https://github.com/PanQiWei/AutoGPTQ)了

@pipixia244 AutoGptQ 量化baichuan2-13b-base没问题，但是量化baichuan2-13b-chat会报错，大佬有遇到过吗
[issue AutoGPTQ](https://github.com/PanQiWei/AutoGPTQ/issues/372)
