### ISSUE TITLE
No such file or directory: 'baichuan-inc/Baichuan2-13B-Chat-4bits/pytorch_model.bin'，如何解决Baichuan2-13B-Chat-4bits不能运行

### ISSUE THREAD

**Issue by RealJianhua** [baichuan-inc/Baichuan2#134]
1. 试运行成功：
python cli_demo.py
但 CUDA out of memory，因此考虑4bits

2. 修改cli_demo.py
修改点是init_model中的模型名字：Baichuan2-13B-Chat -> Baichuan2-13B-Chat-4bits

> def init_model():
    print("init model ...")
    model = AutoModelForCausalLM.from_pretrained(
        "baichuan-inc/Baichuan2-13B-Chat-4bits",
        device_map="auto",
        trust_remote_code=True
    )
    model.generation_config = GenerationConfig.from_pretrained(
        "baichuan-inc/Baichuan2-13B-Chat"
    )
    tokenizer = AutoTokenizer.from_pretrained(
        "baichuan-inc/Baichuan2-13B-Chat",
        use_fast=False,
        trust_remote_code=True
    )
    return model, tokenizer

3. 运行失败：FileNotFoundError: [Errno 2] No such file or directory: 'baichuan-inc/Baichuan2-13B-Chat-4bits/pytorch_model.bin'
细节：

> init model ...
Traceback (most recent call last):
  File "/var/www/baichuan2/Baichuan2/cli_demo_4bits.py", line 86, in <module>
    main()
  File "/var/www/baichuan2/Baichuan2/cli_demo_4bits.py", line 47, in main
    model, tokenizer = init_model()
  File "/var/www/baichuan2/Baichuan2/cli_demo_4bits.py", line 13, in init_model
    model = AutoModelForCausalLM.from_pretrained(
  File "/var/www/baichuan2/Baichuan2/venv/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 558, in from_pretrained
    return model_class.from_pretrained(
  File "/home/wordflow/.cache/huggingface/modules/transformers_modules/baichuan-inc/Baichuan2-13B-Chat-4bits/9b37dd813b19a11925cfe57ad322e602f83298af/modeling_baichuan.py", line 619, in from_pretrained
    state_dict = torch.load(model_file, map_location="cpu") 
  File "/var/www/baichuan2/Baichuan2/venv/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/var/www/baichuan2/Baichuan2/venv/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/var/www/baichuan2/Baichuan2/venv/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'baichuan-inc/Baichuan2-13B-Chat-4bits/pytorch_model.bin'

4. 本地软件环境
Python 3.10.12
---
Package                       Version
accelerate                    0.23.0
altair                        5.1.1
attrs                         23.1.0
bitsandbytes                  0.41.1
blinker                       1.6.2
cachetools                    5.3.1
certifi                       2023.7.22
charset-normalizer            3.2.0
click                         8.1.7
cmake                         3.27.5
colorama                      0.4.6
cpm-kernels                   1.0.11
filelock                      3.12.4
fsspec                        2023.9.1
gitdb                         4.0.10
GitPython                     3.1.36
huggingface-hub               0.17.1
idna                          3.4
importlib-metadata            6.8.0
Jinja2                        3.1.2
jsonschema                    4.19.0
jsonschema-specifications     2023.7.1
lit                           16.0.6
markdown-it-py                3.0.0
MarkupSafe                    2.1.3
mdurl                         0.1.2
mpmath                        1.3.0
networkx                      3.1
numpy                         1.26.0
nvidia-cublas-cu11            11.10.3.66
nvidia-cuda-cupti-cu11        11.7.101
nvidia-cuda-nvrtc-cu11        11.7.99
nvidia-cuda-runtime-cu11      11.7.99
nvidia-cudnn-cu11             8.5.0.96
nvidia-cufft-cu11             10.9.0.58
nvidia-curand-cu11            10.2.10.91
nvidia-cusolver-cu11          11.4.0.1
nvidia-cusparse-cu11          11.7.4.91
nvidia-nccl-cu11              2.14.3
nvidia-nvtx-cu11              11.7.91
packaging                     23.1
pandas                        2.1.0
Pillow                        9.5.0
pip                           22.0.2
protobuf                      4.24.3
psutil                        5.9.5
pyarrow                       13.0.0
pydeck                        0.8.0
Pygments                      2.16.1
Pympler                       1.0.1
python-dateutil               2.8.2
pytz                          2023.3.post1
pytz-deprecation-shim         0.1.0.post0
PyYAML                        6.0.1
referencing                   0.30.2
regex                         2023.8.8
requests                      2.31.0
rich                          13.5.3
rpds-py                       0.10.3
safetensors                   0.3.3
scipy                         1.11.2
sentencepiece                 0.1.99
setuptools                    59.6.0
six                           1.16.0
smmap                         5.0.1
streamlit                     1.26.0
sympy                         1.12
tenacity                      8.2.3
tokenizers                    0.13.3
toml                          0.10.2
toolz                         0.12.0
torch                         2.0.1
tornado                       6.3.3
tqdm                          4.66.1
transformers                  4.33.2
transformers-stream-generator 0.0.4
triton                        2.0.0
typing_extensions             4.8.0
tzdata                        2023.3
tzlocal                       4.3.1
urllib3                       2.0.4
validators                    0.22.0
watchdog                      3.0.0
wheel                         0.41.2
xformers                      0.0.21
zipp                          3.16.2

**Comment by huzuoliang** [comment]
```python
from huggingface_hub import snapshot_download

snapshot_download(repo_id="baichuan-inc/Baichuan2-13B-Chat-4bits", local_dir="baichuan-inc/Baichuan2-13B-Chat-4bits")
```

**Comment by wencan** [comment]
@huzuoliang 不是应该自动下载吗？

**Comment by qianma819** [comment]
@RealJianhua 请问你这个环境可以跑起来13b-chat-4bits么？我用的你这个环境，总是提示：KeyError: 'st.session_state has no key "messages".

**Comment by RealJianhua** [comment]
@qianma819 可以跑，
使用这个方法：

> ```python
> snapshot_download(repo_id="baichuan-inc/Baichuan2-13B-Chat-4bits", local_dir="baichuan-inc/Baichuan2-13B-Chat-4bits")
> ```
