### ISSUE TITLE
量化时报错

### ISSUE THREAD

**Issue by sunsssyc** [baichuan-inc/Baichuan2#144]
ImportError: This modeling file requires the following packages that were not found in your environment: accelerate. Run `pip install accelerate`

代码
from transformers import AutoModelForCausalLM

def save_int8(quant8_saved_dir,model_path):
    model = AutoModelForCausalLM.from_pretrained(model_path, load_in_8bit=True, device_map="auto", trust_remote_code=True)
    model.save_pretrained(quant8_saved_dir)
    model = AutoModelForCausalLM.from_pretrained(quant8_saved_dir, device_map="auto", trust_remote_code=True)

if __name__ == '__main__':
    save_path = '/root/autodl-tmp/baichuan_bit/int8'
    model_path = '/root/autodl-tmp/baichuan13b2'
    save_int8(save_path,model_path)

按提示执行pip install accelerate 依然报这个错

**Comment by gujie01** [comment]
安装包问题，进fine-tune文件直接pip install -r requirements.txt 
 就是这个文件https://github.com/baichuan-inc/Baichuan2/blob/main/fine-tune/requirements.txt，安装包的依赖挺麻烦的，建议conda一个新环境，从零搭建

**Comment by sunsssyc** [comment]
好了
