### ISSUE TITLE
多轮对话记忆问题

### ISSUE THREAD

**Issue by ltm920716** [baichuan-inc/Baichuan2#154]
hello，
chat模式可以完成对话，但是并不会记忆对话历史内容，每次的回答依然只能按照最新一次的user信息回复，history传递到chat()中也没用，这个是因为过拟合了么，还是因为没有instruct的缘故，有同学有解决方案么，

另外chatglm也没有instruct，但是对话的记忆能力似乎比baichuan2-chat要强，是过拟合了？

**Comment by tkone2018** [comment]
@ltm920716 你好，请问你解决了吗

**Comment by ltm920716** [comment]
@tkone2018 baichuan2-chat是有记忆能力的，之前测试之所以出现了问题是因为使用了fastchat框架导致的，直接用huggingface的baichuan2服务代码启动没有问题
