### ISSUE TITLE
在不使用xformers加速的情况下是否可以统一13B和7B的attention部分代码

### ISSUE THREAD

**Issue by tsingcoo** [baichuan-inc/Baichuan2#159]
用13B的红框中的代码把7B红框中的代码替换掉
13B的部分代码如下：
<img width="1147" alt="截屏2023-09-20 20 34 38" src="https://github.com/baichuan-inc/Baichuan2/assets/7556825/ff700819-be29-4cf6-b939-f2321e832801">

7B的部分代码如下：
<img width="1144" alt="截屏2023-09-20 20 34 51" src="https://github.com/baichuan-inc/Baichuan2/assets/7556825/b7d43460-2166-499e-9686-53aa60b06427">

**Comment by mmmans** [comment]
Yes, you can.

**Comment by tsingcoo** [comment]
work, thanks.
