### ISSUE TITLE
Baichuan2-13B-chat模型推理，无法限制推理tokens

### ISSUE THREAD

**Issue by cccgw** [baichuan-inc/Baichuan2#160]
model = AutoModelForCausalLM.from_pretrained(args.base_model, device_map="auto", torch_dtype=torch.float16, trust_remote_code=True)
tokenizer = AutoTokenizer.from_pretrained(args.base_model,use_fast=False, trust_remote_code=True )
data =  model.chat(tokenizer, "请罗列中国各个城市并做简要介绍”)
目前我基于Baichuan2-13B-chat搭了个API提供前台web查询，
对于这类问题，如果提问的人想提前结束这个回答，如何结束。目前情况是前台关闭socket请求了，后台GPU还在不断推理。
而新的问题并发进来后，GPU因为之前的请求还在计算而消耗性能。

而如果设置max_tokens是不支持的：
data =  model.chat(tokenizer, "请罗列中国各个城市并做简要介绍”,max_tokens=100)
TypeError: chat() got an unexpected keyword argument 'max_tokens'，目前不知道除了stream外，还有哪些参数可以通过chat方法进来。

而如果用chat模型，使用modle.generate的话，回答效果比chat差很多。

**Comment by cccgw** [comment]
model.generation_config.max_new_tokens=100 有效。

**Comment by ann22** [comment]
> model.generation_config.max_new_tokens=100 有效。

您好，我设置了100，多次实验结果都超出100
