### ISSUE TITLE
Baichuan2会支持langChain调用么

### ISSUE THREAD

**Issue by WMeng1** [baichuan-inc/Baichuan2#164]
Baichuan2会支持langChain之类的工具调用么？

**Comment by linglingfengty** [comment]
可以自己封装一下吧

**Comment by zhouzhou0322** [comment]
一个workaround 实用vllm部署 vllm提供openai接口形式的http服务。然后langchain直接当做openai调用可以的了

**Comment by WMeng1** [comment]
> 一个workaround 实用vllm部署 vllm提供openai接口形式的http服务。然后langchain直接当做openai调用可以的了

没想到这个思路，谢谢

**Comment by billvsme** [comment]
可以自己实现OpenAI api接口，然后替换langchain中的openai_api_base 
参考实现：https://github.com/billvsme/my_openai_api
