### ISSUE TITLE
百川 2 究竟是不是免费可商用的？

### ISSUE THREAD

**Issue by liwenju0** [baichuan-inc/Baichuan2#166]
看到有的朋友说，申请免费商用授权，被要求收费。
贵司可以将商用授权政策再做个详细的说明吗？谢谢

**Comment by GradientGuru** [comment]
Baichuan 2 是**免费可商用**的。我们在我们的官方文档和授权文件中都明确表示了这一点。
请你跟朋友确认一下他申请的是不是百川，以及请他给出消息来源。

**Comment by liwenju0** [comment]
可否在这里声明一下，以便大家更能无顾虑地使用。
![image](https://github.com/baichuan-inc/Baichuan2/assets/16049564/745ce8d1-2acb-4e86-b8c8-8f0b32886352)
