### ISSUE TITLE
13B-Chat模型checkpoint 加载失败

### ISSUE THREAD

**Issue by dyk0320** [baichuan-inc/Baichuan2#169]
load的时候报错“ValueError: Trying to set a tensor of shape torch.Size([64000, 5120]) in "weight" (which has shape torch.Size([125696, 5120])), this look incorrect.”
请问有人碰到过同样的问题嘛？

**Comment by hardfish82** [comment]
这个问题解决了吗？

**Comment by dyk0320** [comment]
> 这个问题解决了吗？

解决了，用程序自动从huggingface下载的bin文件就没问题。。之前我是手动下的文件，不知道哪里出错了。

**Comment by hardfish82** [comment]
> > 这个问题解决了吗？
> 
> 解决了，用程序自动从huggingface下载的bin文件就没问题。。之前我是手动下的文件，不知道哪里出错了。

我是7B微调得到的中间Checkpoint文件，用peft加载的时候，会报这个错误，看来是不一样的问题。
model = AutoPeftModelForCausalLM.from_pretrained(fine_tune_path, trust_remote_code=True)

  File "/home/hpc/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PeftModelForCausalLM:
        size mismatch for base_model.model.model.layers.0.self_attn.W_pack.lora_A.default.weight: copying a param with shape torch.Size([2, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.0.self_attn.W_pack.lora_B.default.weight: copying a param with shape torch.Size([8192, 1, 1]) from checkpoint, the shape in current model is torch.Size([12288, 1]).
        size mismatch for base_model.model.model.layers.1.self_attn.W_pack.lora_A.default.weight: copying a param with shape torch.Size([2, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.1.self_attn.W_pack.lora_B.default.weight: copying a param with shape torch.Size([8192, 1, 1]) from checkpoint, the shape in current model is torch.Size([12288, 1]).
        size mismatch for base_model.model.model.layers.2.self_attn.W_pack.lora_A.default.weight: copying a param with shape torch.Size([2, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.2.self_attn.W_pack.lora_B.default.weight: copying a param with shape torch.Size([8192, 1, 1]) from checkpoint, the shape in current model is torch.Size([12288, 1]).
        size mismatch for base_model.model.model.layers.3.self_attn.W_pack.lora_A.default.weight: copying a param with shape torch.Size([2, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.3.self_attn.W_pack.lora_B.default.weight: copying a param with shape torch.Size([8192, 1, 1]) from checkpoint, the shape in current model is torch.Size([12288, 1]).
        size mismatch for base_model.model.model.layers.4.self_attn.W_pack.lora_A.default.weight: copying a param with shape torch.Size([2, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.4.self_attn.W_pack.lora_B.default.weight: copying a param with shape torch.Size([8192, 1, 1]) from checkpoint, the shape in current model is torch.Size([12288, 1]).
        size mismatch for base_model.model.model.layers.5.self_attn.W_pack.lora_A.default.weight: copying a param with shape torch.Size([2, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.5.self_attn.W_pack.lora_B.default.weight: copying a param with shape torch.Size([8192, 1, 1]) from checkpoint, the shape in current model is torch.Size([12288, 1]).
        size mismatch for base_model.model.model.layers.6.self_attn.W_pack.lora_A.default.weight: copying a param with shape torch.Size([2, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.6.self_attn.W_pack.lora_B.default.weight: copying a param with shape torch.Size([8192, 1, 1]) from checkpoint, the shape in current model is torch.Size([12288, 1]).
        size mismatch for base_model.model.model.layers.7.self_attn.W_pack.lora_A.default.weight: copying a param with shape torch.Size([2, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.7.self_attn.W_pack.lora_B.default.weight: copying a param with shape torch.Size([8192, 1, 1]) from checkpoint, the shape in current model is torch.Size([12288, 1]).
        size mismatch for base_model.model.model.layers.8.self_attn.W_pack.lora_A.default.weight: copying a param with shape torch.Size([2, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.8.self_attn.W_pack.lora_B.default.weight: copying a param with shape torch.Size([8192, 1, 1]) from checkpoint, the shape in current model is torch.Size([12288, 1]).
        size mismatch for base_model.model.model.layers.9.self_attn.W_pack.lora_A.default.weight: copying a param with shape torch.Size([2, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.9.self_attn.W_pack.lora_B.default.weight: copying a param with shape torch.Size([8192, 1, 1]) from checkpoint, the shape in current model is torch.Size([12288, 1]).
        size mismatch for base_model.model.model.layers.10.self_attn.W_pack.lora_A.default.weight: copying a param with shape torch.Size([2, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.10.self_attn.W_pack.lora_B.default.weight: copying a param with shape torch.Size([8192, 1, 1]) from checkpoint, the shape in current model is torch.Size([12288, 1]).
        size mismatch for base_model.model.model.layers.11.self_attn.W_pack.lora_A.default.weight: copying a param with shape torch.Size([2, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.11.self_attn.W_pack.lora_B.default.weight: copying a param with shape torch.Size([8192, 1, 1]) from checkpoint, the shape in current model is torch.Size([12288, 1]).
        size mismatch for base_model.model.model.layers.12.self_attn.W_pack.lora_A.default.weight: copying a param with shape torch.Size([2, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.12.self_attn.W_pack.lora_B.default.weight: copying a param with shape torch.Size([8192, 1, 1]) from checkpoint, the shape in current model is torch.Size([12288, 1]).
        size mismatch for base_model.model.model.layers.13.self_attn.W_pack.lora_A.default.weight: copying a param with shape torch.Size([2, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.13.self_attn.W_pack.lora_B.default.weight: copying a param with shape torch.Size([8192, 1, 1]) from checkpoint, the shape in current model is torch.Size([12288, 1]).
        size mismatch for base_model.model.model.layers.14.self_attn.W_pack.lora_A.default.weight: copying a param with shape torch.Size([2, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.14.self_attn.W_pack.lora_B.default.weight: copying a param with shape torch.Size([8192, 1, 1]) from checkpoint, the shape in current model is torch.Size([12288, 1]).
        size mismatch for base_model.model.model.layers.15.self_attn.W_pack.lora_A.default.weight: copying a param with shape torch.Size([2, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.15.self_attn.W_pack.lora_B.default.weight: copying a param with shape torch.Size([8192, 1, 1]) from checkpoint, the shape in current model is torch.Size([12288, 1]).
        size mismatch for base_model.model.model.layers.16.self_attn.W_pack.lora_A.default.weight: copying a param with shape torch.Size([2, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.16.self_attn.W_pack.lora_B.default.weight: copying a param with shape torch.Size([8192, 1, 1]) from checkpoint, the shape in current model is torch.Size([12288, 1]).
        size mismatch for base_model.model.model.layers.17.self_attn.W_pack.lora_A.default.weight: copying a param with shape torch.Size([2, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.17.self_attn.W_pack.lora_B.default.weight: copying a param with shape torch.Size([8192, 1, 1]) from checkpoint, the shape in current model is torch.Size([12288, 1]).
        size mismatch for base_model.model.model.layers.18.self_attn.W_pack.lora_A.default.weight: copying a param with shape torch.Size([2, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.18.self_attn.W_pack.lora_B.default.weight: copying a param with shape torch.Size([8192, 1, 1]) from checkpoint, the shape in current model is torch.Size([12288, 1]).
        size mismatch for base_model.model.model.layers.19.self_attn.W_pack.lora_A.default.weight: copying a param with shape torch.Size([2, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.19.self_attn.W_pack.lora_B.default.weight: copying a param with shape torch.Size([8192, 1, 1]) from checkpoint, the shape in current model is torch.Size([12288, 1]).
        size mismatch for base_model.model.model.layers.20.self_attn.W_pack.lora_A.default.weight: copying a param with shape torch.Size([2, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.20.self_attn.W_pack.lora_B.default.weight: copying a param with shape torch.Size([8192, 1, 1]) from checkpoint, the shape in current model is torch.Size([12288, 1]).
        size mismatch for base_model.model.model.layers.21.self_attn.W_pack.lora_A.default.weight: copying a param with shape torch.Size([2, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.21.self_attn.W_pack.lora_B.default.weight: copying a param with shape torch.Size([8192, 1, 1]) from checkpoint, the shape in current model is torch.Size([12288, 1]).
        size mismatch for base_model.model.model.layers.22.self_attn.W_pack.lora_A.default.weight: copying a param with shape torch.Size([2, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.22.self_attn.W_pack.lora_B.default.weight: copying a param with shape torch.Size([8192, 1, 1]) from checkpoint, the shape in current model is torch.Size([12288, 1]).
        size mismatch for base_model.model.model.layers.23.self_attn.W_pack.lora_A.default.weight: copying a param with shape torch.Size([2, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.23.self_attn.W_pack.lora_B.default.weight: copying a param with shape torch.Size([8192, 1, 1]) from checkpoint, the shape in current model is torch.Size([12288, 1]).
        size mismatch for base_model.model.model.layers.24.self_attn.W_pack.lora_A.default.weight: copying a param with shape torch.Size([2, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.24.self_attn.W_pack.lora_B.default.weight: copying a param with shape torch.Size([8192, 1, 1]) from checkpoint, the shape in current model is torch.Size([12288, 1]).
        size mismatch for base_model.model.model.layers.25.self_attn.W_pack.lora_A.default.weight: copying a param with shape torch.Size([2, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.25.self_attn.W_pack.lora_B.default.weight: copying a param with shape torch.Size([8192, 1, 1]) from checkpoint, the shape in current model is torch.Size([12288, 1]).
        size mismatch for base_model.model.model.layers.26.self_attn.W_pack.lora_A.default.weight: copying a param with shape torch.Size([2, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.26.self_attn.W_pack.lora_B.default.weight: copying a param with shape torch.Size([8192, 1, 1]) from checkpoint, the shape in current model is torch.Size([12288, 1]).
        size mismatch for base_model.model.model.layers.27.self_attn.W_pack.lora_A.default.weight: copying a param with shape torch.Size([2, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.27.self_attn.W_pack.lora_B.default.weight: copying a param with shape torch.Size([8192, 1, 1]) from checkpoint, the shape in current model is torch.Size([12288, 1]).
        size mismatch for base_model.model.model.layers.28.self_attn.W_pack.lora_A.default.weight: copying a param with shape torch.Size([2, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.28.self_attn.W_pack.lora_B.default.weight: copying a param with shape torch.Size([8192, 1, 1]) from checkpoint, the shape in current model is torch.Size([12288, 1]).
        size mismatch for base_model.model.model.layers.29.self_attn.W_pack.lora_A.default.weight: copying a param with shape torch.Size([2, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.29.self_attn.W_pack.lora_B.default.weight: copying a param with shape torch.Size([8192, 1, 1]) from checkpoint, the shape in current model is torch.Size([12288, 1]).
        size mismatch for base_model.model.model.layers.30.self_attn.W_pack.lora_A.default.weight: copying a param with shape torch.Size([2, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.30.self_attn.W_pack.lora_B.default.weight: copying a param with shape torch.Size([8192, 1, 1]) from checkpoint, the shape in current model is torch.Size([12288, 1]).
        size mismatch for base_model.model.model.layers.31.self_attn.W_pack.lora_A.default.weight: copying a param with shape torch.Size([2, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.31.self_attn.W_pack.lora_B.default.weight: copying a param with shape torch.Size([8192, 1, 1]) from checkpoint, the shape in current model is torch.Size([12288, 1]).
不知道最终保存的权重，和中间过程的checkpoint有没有差异？

**Comment by linxh91** [comment]
我也出现了这个问题，请问你最后解决了吗？

**Comment by dyk0320** [comment]
> 我也出现了这个问题，请问你最后解决了吗？

上面说了呀，重新下载模型后没问题了

**Comment by dyk0320** [comment]
应该是模型下载的问题，重新下了一个好了

**Comment by linxh91** [comment]
我开始是直接在hg上手动下载的main分支的出现这个问题，后面我选到v1.1的分支全部模型重新下了一遍就可以了
