### ISSUE TITLE
请教下，如何读取微调后的模型进行使用？

### ISSUE THREAD

**Issue by dreamer1997** [baichuan-inc/Baichuan2#177]
![image](https://github.com/baichuan-inc/Baichuan2/assets/37857758/7a2b4661-77ff-4c27-8e81-e8f9c3018c26)
微调后的结果如图所示，看readme里也没有关于这块的内容，不太清楚应该怎么处理微调后的模型，请教下各位大佬有没有这方面的教程。

**Comment by piwawa** [comment]
> ![image](https://user-images.githubusercontent.com/37857758/270326911-7a2b4661-77ff-4c27-8e81-e8f9c3018c26.png) 微调后的结果如图所示，看readme里也没有关于这块的内容，不太清楚应该怎么处理微调后的模型，请教下各位大佬有没有这方面的教程。

咋解决的？这问题很有价值啊

**Comment by cuisws** [comment]
> ![image](https://user-images.githubusercontent.com/37857758/270326911-7a2b4661-77ff-4c27-8e81-e8f9c3018c26.png) 微调后的结果如图所示，看readme里也没有关于这块的内容，不太清楚应该怎么处理微调后的模型，请教下各位大佬有没有这方面的教程。

加载路径是哪个

**Comment by cuisws** [comment]
> ![image](https://user-images.githubusercontent.com/37857758/270326911-7a2b4661-77ff-4c27-8e81-e8f9c3018c26.png) 微调后的结果如图所示，看readme里也没有关于这块的内容，不太清楚应该怎么处理微调后的模型，请教下各位大佬有没有这方面的教程。

请问加载路径是最后的checkpoint还是output

**Comment by cuisws** [comment]
> ![image](https://user-images.githubusercontent.com/37857758/270326911-7a2b4661-77ff-4c27-8e81-e8f9c3018c26.png) 微调后的结果如图所示，看readme里也没有关于这块的内容，不太清楚应该怎么处理微调后的模型，请教下各位大佬有没有这方面的教程。

请问加载路径是最后的checkpoint还是output，我都可以正常启动

**Comment by JJASMINE22** [comment]
亲测，务必将lora迁移训练得到的模型目录“output”放置在baichuan-inc官方模型目录的同级目录下，且推理脚本inference.py也与它们同级，否则异常
![image](https://github.com/baichuan-inc/Baichuan2/assets/71243616/f13ac1b6-913c-4561-9267-158874b26176)
inference.py中的加载过程如下：
`
import torch
from peft import AutoPeftModelForCausalLM
from transformers import AutoTokenizer
from transformers.generation.utils import GenerationConfig

tokenizer = AutoTokenizer.from_pretrained("BaiChuan-Inc/Baichuan2-7B-Chat", use_fast=False,
                                          trust_remote_code=True)
model = AutoPeftModelForCausalLM.from_pretrained("output", trust_remote_code=True, device_map="auto", torch_dtype=torch.bfloat16)
model.generation_config = GenerationConfig.from_pretrained("BaiChuan-Inc/Baichuan2-7B-Chat")
`
