### ISSUE TITLE
4bits微调问题

### ISSUE THREAD

**Issue by cuisws** [baichuan-inc/Baichuan2#205]
ValueError: The model you want to train is loaded in 8-bit precision.  if you want to fine-tune an 8-bit model, please make sure that you have installed `bitsandbytes>=0.37.0`. 
我已经pip install bitsandbytes==0.41.1

**Comment by dage0127** [comment]
上述提示不对，误导。
4bits不能微调，用7B-Chat可以。

**Comment by GitMonkey0** [comment]
搞了一上午，然后不能微调，服气（-_-）
