### ISSUE TITLE
huggingface模型内部缺少文件

### ISSUE THREAD

**Issue by Flywolfs** [baichuan-inc/Baichuan2#21]
刚刚运行web_demo.py，报错误：OSError: /media/calvin/new_disk1/models/Baichuan2-7B-Base does not appear to have a file named generation_config.json. Checkout 'https://huggingface.co//media/calvin/new_disk1/models/Baichuan2-7B-Base/None' for available files.
去huggingface看确实缺少generation_config.json文件。请问是没上传吗？

**Comment by GradientGuru** [comment]
你下载的是Base模型。Chat 模型才支持 web_demo.py 和 cli_demo.py
