### ISSUE TITLE
pad_token_id配置多处不一致问题

### ISSUE THREAD

**Issue by gavin1332** [baichuan-inc/Baichuan2#210]
在`Baichuan2-7B-Chat/config.json`里，`"pad_token_id": 0,`，而在`Baichuan2-7B-Chat/added_tokens.json`里，`"<pad>": 125696`，应该以哪个为准？

**Comment by gavin1332** [comment]
并且在`Baichuan2-7B-Chat/special_tokens_map.json`里，
`  "pad_token": {
    "content": "<unk>",
    "lstrip": false,
    "normalized": true,
    "rstrip": false,
    "single_word": false
  },`
<unk>对应的id是0。

**Comment by gavin1332** [comment]
并且在`Baichuan2-7B-Chat/tokenizer_config.json`里，
```
  "pad_token": {
    "__type": "AddedToken",
    "content": "<unk>",
    "lstrip": false,
    "normalized": true,
    "rstrip": false,
    "single_word": true
  }, 
```
pad_token的content是<unk>而非<pad>

**Comment by gauss-clb** [comment]
pad_token就是<unk>，从llama一直用的这个，add_token.json是用来加新词的，需要resize_token_embeddings之后重新训，<pad>应该是baichuan之前预训练忘记加的token吧，但这个token并不当做pad_token用，而且baichuan词表只有125696，如果想单独编码<pad>需要自己训，否则语料中一旦出现<pad>则会出现数组越界错误，https://github.com/baichuan-inc/Baichuan2/issues/72

**Comment by gavin1332** [comment]
3KS
