### ISSUE TITLE
对 Baichuan 1 的推理优化迁移到 Baichuan 2的转化代码有问题

### ISSUE THREAD

**Issue by Zhang-star-master** [baichuan-inc/Baichuan2#22]
![image](https://github.com/baichuan-inc/Baichuan2/assets/25812074/bddd5b16-089a-4354-9664-62e3d5ede217)
下载的模型文件里面有三个.bin的文件  提供的代码会报错

**Comment by FrankWhh** [comment]
可以看index json文件，确定lm_head在哪个bin文件下

**Comment by daxia-daxia** [comment]
> ![image](https://user-images.githubusercontent.com/25812074/265960715-bddd5b16-089a-4354-9664-62e3d5ede217.png) 下载的模型文件里面有三个.bin的文件 提供的代码会报错

The sample code is just an explanation of the translation process.  You should change this accordding your situation. If you download from hf repo. Change 'pytorch_model.bin' to 'pytorch_model-00002-of-00002.bin' maybe work!
![image](https://github.com/baichuan-inc/Baichuan2/assets/24487097/731455f8-169b-43ba-ad11-1a6978cdce5a)

**Comment by boxter007** [comment]
> > ![image](https://user-images.githubusercontent.com/25812074/265960715-bddd5b16-089a-4354-9664-62e3d5ede217.png) 下载的模型文件里面有三个.bin的文件 提供的代码会报错
> 
> The sample code is just an explanation of the translation process. You should change this accordding your situation. If you download from hf repo. Change 'pytorch_model.bin' to 'pytorch_model-00002-of-00002.bin' maybe work! ![image](https://user-images.githubusercontent.com/24487097/265971073-731455f8-169b-43ba-ad11-1a6978cdce5a.png)

我找到了lm_head_weight 在 00003.bin上，修改代码中得文件名后运行，报错：
Attempting to deserialize object on CUDA device 5 but torch.cuda.device_count() is 2. Please use torch.load with map_location to map your storages to an existing device.
我机器上只有2个GPU不知道为什么会出现 CUDA device 5

**Comment by daxia-daxia** [comment]
Because the original tensor saved are on 8 GPU. And saved tensors record its device info. It will try to put tensor to their device if you load by default. You can  try 
```
state_dict = torch.load(path, map_location='cpu')
```
or
```
state_dict = torch.load(path, map_location='cuda:0')
```
to specify the device.

**Comment by Zhang-star-master** [comment]
增加map_location参数就可以
torch.load(model_path, map_location='cuda:0')
