### ISSUE TITLE
user_token和assistant_token有对应的明文吗？

### ISSUE THREAD

**Issue by greyamber** [baichuan-inc/Baichuan2#239]
如题，我在使用llama.cpp运行百川2 13B，发现多轮对话的分隔符在百川官方pytorch版本的demo中是直接用generation_config.json里配置好的，而不是用明文拼接后tokenizer自动生成的。
有办法不做一些额外的处理（比如改llama.cpp代码，自己增加词表映射等）来处理正确的拼接多轮对话的prompt吗？

**Comment by greyamber** [comment]
已经解决。分别是
<reserved_106> <reserved_107>

**Comment by apepkuss** [comment]
@greyamber 你好，请问是否可以给个多轮对话prompt字符串形式的例子么？多谢！
