### ISSUE TITLE
Is the norm dim In NormHead right?

### ISSUE THREAD

**Issue by butterluo** [baichuan-inc/Baichuan2#247]
I found that 'norm_weight = nn.functional.normalize(self.weight)' in modeling_baichuan.py. But the shape of weight is (vocab_size, hidden_size). Should it change to nn.functional.normalize(self.weight, dim=1) ? Or, am I miss something ?

**Comment by jameswu2014** [comment]
> I found that 'norm_weight = nn.functional.normalize(self.weight)' in modeling_baichuan.py. But the shape of weight is (vocab_size, hidden_size). Should it change to nn.functional.normalize(self.weight, dim=1) ? Or, am I miss something ?

The two methods is not the same?

**Comment by butterluo** [comment]
Sorry, I thought the default value is dim=0. Yes they are the same, the default dim=1
