### ISSUE TITLE
请问 WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions 这个警告影响chat运行么？

### ISSUE THREAD

**Issue by zhangke-zhangke** [baichuan-inc/Baichuan2#248]
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.0+cu121 with CUDA 1201 (you have 2.1.0+cpu)
    Python  3.8.10 (you have 3.8.0)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details

**Comment by ghkl98** [comment]
请问解决了吗，怎么解决的啊

**Comment by jameswu2014** [comment]
没影响
