### ISSUE TITLE
[Evaluation] 提供 Baichuan2 模型在 OpenCompass 上的评测结果

### ISSUE THREAD

**Issue by Leymore** [baichuan-inc/Baichuan2#26]
我们在 opencompass 上对 Baichuan2-7B-Base / Baichuan2-7B-Chat / Baichuan2-13B-Base / Baichuan2-13B-Chat 模型进行了评测，评测结果如下：

![img_v2_963bb47b-f8d8-47b5-8cf2-48a22afea0dg](https://github.com/baichuan-inc/Baichuan2/assets/17680578/83919fa4-a6b9-4ac9-a191-c1ca4dc4da4b)
![img_v2_d2cdf1f7-e821-4e9e-9515-16ad19529b4g](https://github.com/baichuan-inc/Baichuan2/assets/17680578/5bee93d3-8e23-495d-8e97-90220dda62da)
![img_v2_9b962d7e-edb4-4fe9-95f4-2f335ab9212g](https://github.com/baichuan-inc/Baichuan2/assets/17680578/81e51149-6dc3-47bc-b5e2-f6bfdd9025b3)
![img_v2_f46e3ac4-68ef-4b73-8f51-cacc53f827dg](https://github.com/baichuan-inc/Baichuan2/assets/17680578/1245d30d-ccb7-420e-bf1a-0fbc37682e5b)

![image](https://github.com/baichuan-inc/Baichuan-13B/assets/17680578/c3736277-e211-4c94-9872-651bf8c276e3)

更多评测细节请见 https://opencompass.org.cn/leaderboard-llm

评测交流群链接：https://cdn.vansin.top/opencompass/baichuan.jpg

![img_v2_db03c346-681b-479a-a70e-17355ec69e4g](https://github.com/baichuan-inc/Baichuan-7B/assets/17680578/fc93eb04-699b-4a89-a8ce-7ee7267198e9)

**Comment by GradientGuru** [comment]
👍 👍
