### ISSUE TITLE
about temperature 

### ISSUE THREAD

**Issue by bugm** [baichuan-inc/Baichuan2#260]
is there any method to set the temperature  parameter for different chat except editing the value in file "generation_config.json " By the way, why the temperature parameter is 0.1 according to the paper Baichuan 2: Open Large-scale Language Models while the default value in generation_config.json is 0.3

**Comment by FragrantDark** [comment]
try this way:
```
g_config=copy.deepcopy(model.generation_config)
g_config.temperature = 0.9
model.chat(tokenizer, messages, generation_config=g_config)
```
