### ISSUE TITLE
这回答的偏差有点大，把侠客行和将进酒搞混了

### ISSUE THREAD

**Issue by heiheiheibj** [baichuan-inc/Baichuan2#27]
![微信截图_20230906232329](https://github.com/baichuan-inc/Baichuan2/assets/6910198/09d19d38-1fae-4e19-8019-a0505b1c3e41)

**Comment by MOLIZHU2023** [comment]
![af1e1bfb817eebd4404848fe4ed46f0](https://github.com/baichuan-inc/Baichuan2/assets/128791934/cc2c2ea5-8d5b-4683-97c5-e5dce01ed3cb)
![c755bc0b12e31b223e0486ad101d4c7](https://github.com/baichuan-inc/Baichuan2/assets/128791934/61868a60-f0b0-450f-914b-116e11df51ce)

**Comment by GradientGuru** [comment]
看来是 Baichuan 2 答对了，但是 Baichuan-53B 产生了幻觉
