### ISSUE TITLE
HELP!!!  两块V100运行13B-chat推理巨慢

### ISSUE THREAD

**Issue by garyyang85** [baichuan-inc/Baichuan2#276]
使用fastchat以openai的方式启动的，
```
python3 -m fastchat.serve.controller

python3 -m fastchat.serve.model_worker --model-path /app/model --num-gpus=2 --gpus=0,1 --max-gpu-memory=30GB --model-names=Baichuan2-13B-Chat

python3 -m fastchat.serve.openai_api_server --host 0.0.0.0 --port 8000
```

请问有什么调优的思路没

**Comment by zRzRzRzRzRzRzR** [comment]
模型并行的问题？
肯定是单块更快的

**Comment by garyyang85** [comment]
> 换成一块显卡试试看呢？我用一块V100推理的性能还行

一块V100刚好可以完美运行webdemo，我是用fastchat以openapi的暴露方式启动的，一到长文本的问题推理就自动截断了。开始还以为是token数限制，结果用两块卡推理就没有问题。 但是新的问题就是两块卡并行的推理速度，太慢了。

**Comment by garyyang85** [comment]
> 模型并行的问题？ 肯定是单块更快的

这个是通用问题么？一块卡能力不够，需要多卡推理的场景应该还是挺常见的。现在是速度降了好几倍，几乎不可接受的速度。求指教这个一般是模型自身对多卡并行支持的不好导致的么？

**Comment by KegangWangCCNU** [comment]
如果你的v100是pcie原版（也就是nvidia-smi 显示V100-PCIE），可以添加一个nvlink桥。如果是SXM改的卡就不行了。这应该是两张卡之间带宽瓶颈导致的。

**Comment by zhangapeng** [comment]
请问你最后怎么处理的
