### ISSUE TITLE
这是因为网络问题吗

### ISSUE THREAD

**Issue by ghkl98** [baichuan-inc/Baichuan2#289]
requests.exceptions.ProxyError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /baichuan-inc/Baichuan2-7B-Chat-4bits/resolve/main/config.json (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Service Unavailable')))"), '(Request ID: c0fa8344-60dc-44ad-b2d4-b95e9e2c8330)')

**Comment by baichuan-assistant** [comment]
Huggingface连不上，可以试试Modelscope：https://modelscope.cn/models/baichuan-inc/Baichuan2-13B-Chat
