### ISSUE TITLE
2.6 万亿 Tokens 的高质量语料是训练了 1 个epoch吗？

### ISSUE THREAD

**Issue by ZayIsAllYouNeed** [baichuan-inc/Baichuan2#298]
“Baichuan 2 是百川智能推出的新一代开源大语言模型，采用 2.6 万亿 Tokens 的高质量语料训练。”
请问这个的意思是在包含2.6 万亿个token的数据集训练了一个epoch吗？

**Comment by baichuan-assistant** [comment]
不是的，有关训练细节可以阅读我们的技术报告：https://arxiv.org/abs/2309.10305
