### ISSUE TITLE
训练和推理以及量化占用显存情况

### ISSUE THREAD

**Issue by Jonsun-N** [baichuan-inc/Baichuan2#30]
1、训练显存占用情况；
2、推理显存占用情况，能否支持多卡；
3、推理量化显存占用情况。

**Comment by DuTim** [comment]
有具体的数据吗

**Comment by luckydrq** [comment]
直接关了？

**Comment by yaleimeng** [comment]
第2点简单测试了一下，未量化模型直接fp16推理总显存占用32.5GB左右，可以多卡分摊。我就是2张4090运行的，每张16GB多。
第3点量化没测试，估计显存占用10GB左右。许多显卡都可以支持单卡4bit量化推理。
