### ISSUE TITLE
Baichuan2 为什么不在 attention 中加入 dropout ？

### ISSUE THREAD

**Issue by David-Lee-1990** [baichuan-inc/Baichuan2#312]
如题，Llama2 是有 attention_dropout的
[https://github.com/huggingface/transformers/blob/v4.36.0/src/transformers/models/llama/modeling_llama.py#L430C1-L431C1](url)

但是Baichuan2 没有

**Comment by GradientGuru** [comment]
llama2的默认dropout是0.0
