### ISSUE TITLE
商用授权

### ISSUE THREAD

**Issue by DSXiangLi** [baichuan-inc/Baichuan2#318]
您好，

针对商用授权申请有几个问题，之前发了邮件到申请邮箱还没有回复，想在这里求助下

1. 信息表里申请人联系方式及联系地址，是指公司的注册地址还是办公地址
2. 申请人代理人的身份证复印件并加盖公章，是指我的身份证加盖公章么?
3. 申请人代理人的授权书复印件并加盖公章，这个授权文件在哪里可以找到我在网页里没看到
​
感谢，

**Comment by HGladiator** [comment]
申请人代理人的授权书复印件  是否可能提供一份模板，我也不理解这里的授权书内容如何准备。

**Comment by DSXiangLi** [comment]
> 申请人代理人的授权书复印件 是否可能提供一份模板，我也不理解这里的授权书内容如何准备。

对方以回复我，授权书无模板就是授权你个人为公司申请授权的意思。可以直接参考chatglm的授权书
