### ISSUE TITLE
量化后4bit模型相比于未量化的推理速度好像并没有提升

### ISSUE THREAD

**Issue by xjwspeak** [baichuan-inc/Baichuan2#32]
量化后4bit模型相比于未量化的推理速度好像并没有提升，能解释下么？

Readme里只有显存和精度的对比，能提供下推理速度的对比吗？

**Comment by xjwspeak** [comment]
补充一下：V100，cuda 11.2

**Comment by jameswu2014** [comment]
是的，主要是省显存。

**Comment by LinXin04** [comment]
想问下可以分享下如何量化13B -chat的代码的嘛
