### ISSUE TITLE
Max-z loss

### ISSUE THREAD

**Issue by bpwl0121** [baichuan-inc/Baichuan2#325]
Hi,

where do you use Max-z loss actually？
there is no Max-z loss inside the [base model](https://huggingface.co/baichuan-inc/Baichuan2-7B-Base/blob/main/modeling_baichuan.py), but the [chat version](https://huggingface.co/baichuan-inc/Baichuan2-13B-Chat/blob/main/modeling_baichuan.py). 
So you use the max z loss at the sft?

best,

**Comment by GradientGuru** [comment]
Good day. We do not use z loss during fine-tuning. Default self.config.z_loss_weight is 0.
However thanks for pointing out that we've missed the z_loss code in 7B-Base repo, fixed now.

**Comment by bpwl0121** [comment]
I think you have to update your [config file](https://huggingface.co/baichuan-inc/Baichuan2-7B-Base/blob/main/configuration_baichuan.py) accordingly. there is no z loss weight
