### ISSUE TITLE
运行cli_demo.py显示下面的问题

### ISSUE THREAD

**Issue by Damonpkl** [baichuan-inc/Baichuan2#330]
You are using an old version of the checkpointing format that is deprecated (We will also silently ignore `gradient_checkpointing_kwargs` in case you passed it).Please update to the new format on your modeling file. To use the new format, you need to completely remove the definition of the method `_set_gradient_checkpointing` in your model.
Loading checkpoint shards:   0%|                                                                              | 0/3 [00:00<?, ?it/s]Killed
是版本太低了吗？

**Comment by baichuan-assistant** [comment]
可以去huggingface/modelscope下载最新版本的模型

**Comment by Damonpkl** [comment]
好的谢谢，具体的问题已经解决，首先是transformers版本的问题，最新的版本是 4.36.2,需要降到4.33.2.然后是Loading checkpoint shards出现killed,是内存没给够。
