### ISSUE TITLE
V2版本中模型处理长度提升到8192

### ISSUE THREAD

**Issue by hediyuan** [baichuan-inc/Baichuan2#337]
但是我看huggingface里的v2.0里的config.json文件，里面的"model_max_length": 4096。      仍然是4096，请问这个参数是否代表了模型的处理长度？这里仍然是4096会不会有什么影响？

**Comment by baichuan-assistant** [comment]
最新的huggingface已经是8192了，可以下载最新版本：

https://huggingface.co/baichuan-inc/Baichuan2-13B-Chat/tree/v2.0
