### ISSUE TITLE
Hi, have a question : Baichuan-Text-Embedding can be open for open source or have api to use or pay for use? thanks

### ISSUE THREAD

**Issue by Yazooliu** [baichuan-inc/Baichuan2#341]
Baichuan-Text-Embedding can be open for open source or have api to use or pay for use? thanks

expect your responese.

BR
Yazhou

**Comment by baichuan-assistant** [comment]
It's closed-source

You can use it following: https://platform.baichuan-ai.com/docs/text-Embedding

**Comment by Yazooliu** [comment]
你好，
已经提前查看该链接及社区文档，
当前社区提供的向量模型调用 api token 仅仅对企业用户开放。个人用户在认证阶段并没有开放。
见下图：
百川大模型-汇聚世界知识 创作妙笔生花-百川智能 (baichuan-ai.com)
认证不通过就无法直接试用。






At 2024-01-08 18:12:31, "baichuan-assistant" ***@***.***> wrote:

It's closed-source

You can use it following: https://platform.baichuan-ai.com/docs/text-Embedding

**Comment by baichuan-assistant** [comment]
> 你好， 已经提前查看该链接及社区文档， 当前社区提供的向量模型调用 api token 仅仅对企业用户开放。个人用户在认证阶段并没有开放。 见下图： 百川大模型-汇聚世界知识 创作妙笔生花-百川智能 (baichuan-ai.com) 认证不通过就无法直接试用。 At 2024-01-08 18:12:31, "baichuan-assistant" ***@***.***> wrote: It's closed-source You can use it following: https://platform.baichuan-ai.com/docs/text-Embedding — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

是的，个人认证要等到1月底2月初的样子
