### ISSUE TITLE
问下百川模型有做过算法备案么？

### ISSUE THREAD

**Issue by ljwps** [baichuan-inc/Baichuan2#348]
问下百川模型有做过算法备案么？
目前用模型落地可能需要有相应的备案方面的材料，百川是否已经有了？

**Comment by baichuan-assistant** [comment]
有的噢，百川是第一批通过备案的大模型

**Comment by ljwps** [comment]
> 有的噢，百川是第一批通过备案的大模型

我没有查到么，能提供下备案号么？

**Comment by baichuan-assistant** [comment]
> > 有的噢，百川是第一批通过备案的大模型
> 
> 我没有查到么，能提供下备案号么？ ![image](https://private-user-images.githubusercontent.com/18318466/296112855-63f50922-4c38-4290-abbe-16eba5bf309e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMjk2NzgsIm5iZiI6MTcwNTAyOTM3OCwicGF0aCI6Ii8xODMxODQ2Ni8yOTYxMTI4NTUtNjNmNTA5MjItNGMzOC00MjkwLWFiYmUtMTZlYmE1YmYzMDllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDAzMTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyOGM2M2M3MzVhODAwNGI4MTQ2ZWU0MDQ2Y2JhY2E3NjJkMmE0YWI4MzY4NGVlZDRhYzI5N2NmYmQwMzk2ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f8e3t8MQnytJWZD52n-TOm9H2J2P9lHq8UmqExrPyfg)

我们有红头文件，可以证明我们有牌照。但是因为流程问题，现在网信办的系统上面是没有公式的，还需要时间

**Comment by ljwps** [comment]
> > > 有的噢，百川是第一批通过备案的大模型
> > 
> > 
> > 我没有查到么，能提供下备案号么？ ![image](https://private-user-images.githubusercontent.com/18318466/296112855-63f50922-4c38-4290-abbe-16eba5bf309e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMjk2NzgsIm5iZiI6MTcwNTAyOTM3OCwicGF0aCI6Ii8xODMxODQ2Ni8yOTYxMTI4NTUtNjNmNTA5MjItNGMzOC00MjkwLWFiYmUtMTZlYmE1YmYzMDllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDAzMTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyOGM2M2M3MzVhODAwNGI4MTQ2ZWU0MDQ2Y2JhY2E3NjJkMmE0YWI4MzY4NGVlZDRhYzI5N2NmYmQwMzk2ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f8e3t8MQnytJWZD52n-TOm9H2J2P9lHq8UmqExrPyfg)
> 
> 我们有红头文件，可以证明我们有牌照。但是因为流程问题，现在网信办的系统上面是没有公式的，还需要时间

方便能够提供一下文件或者截图么，git里面如可以发私信，发我私信吧，或者我邮箱rechard_marx@163.com。
主要甲方要我们提供开源模型的资质情况。

**Comment by baichuan-assistant** [comment]
> > > > 有的噢，百川是第一批通过备案的大模型
> > > 
> > > 
> > > 我没有查到么，能提供下备案号么？ ![image](https://private-user-images.githubusercontent.com/18318466/296112855-63f50922-4c38-4290-abbe-16eba5bf309e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMjk2NzgsIm5iZiI6MTcwNTAyOTM3OCwicGF0aCI6Ii8xODMxODQ2Ni8yOTYxMTI4NTUtNjNmNTA5MjItNGMzOC00MjkwLWFiYmUtMTZlYmE1YmYzMDllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDAzMTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyOGM2M2M3MzVhODAwNGI4MTQ2ZWU0MDQ2Y2JhY2E3NjJkMmE0YWI4MzY4NGVlZDRhYzI5N2NmYmQwMzk2ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f8e3t8MQnytJWZD52n-TOm9H2J2P9lHq8UmqExrPyfg)
> > 
> > 
> > 我们有红头文件，可以证明我们有牌照。但是因为流程问题，现在网信办的系统上面是没有公式的，还需要时间
> 
> 方便能够提供一下文件或者截图么，git里面如可以发私信，发我私信吧，或者我邮箱[rechard_marx@163.com](mailto:rechard_marx@163.com)。 主要甲方要我们提供开源模型的资质情况。

春节前后可以看到，可以稍等一下
