### ISSUE TITLE
使用 Baichuan2-13B-Chat-4bits 模型报错

### ISSUE THREAD

**Issue by before31** [baichuan-inc/Baichuan2#35]
1、python3.10
2、按照要求安装了requirements.txt
3、git clone https://huggingface.co/baichuan-inc/Baichuan2-13B-Chat-4bits
4、修改cli_demo.py里面的模型加载代码：
    model = AutoModelForCausalLM.from_pretrained(
        "D:\\2-huggingface\\Baichuan2-13B-Chat-4bits",
        device_map="auto",
        trust_remote_code=True
    )
    model.generation_config = GenerationConfig.from_pretrained(
        "D:\\2-huggingface\\Baichuan2-13B-Chat-4bits"
    )
    tokenizer = AutoTokenizer.from_pretrained(
        "D:\\2-huggingface\\Baichuan2-13B-Chat-4bits",
        use_fast=False,
        trust_remote_code=True
    )
5、执行python cli_demo.py报错：
Exception has occurred: ImportError
Needs import model weight init func to run quantize.
  File "C:\Users\WX\.cache\huggingface\modules\transformers_modules\Baichuan2-13B-Chat-4bits\modeling_baichuan.py", line 606, in from_pretrained
    from .quantizer import init_model_weight_int4
  File "C:\Users\WX\.cache\huggingface\modules\transformers_modules\Baichuan2-13B-Chat-4bits\quantizer.py", line 1, in <module>
    import bitsandbytes as bnb
ModuleNotFoundError: No module named 'scipy'

During handling of the above exception, another exception occurred:

  File "C:\Users\WX\.cache\huggingface\modules\transformers_modules\Baichuan2-13B-Chat-4bits\modeling_baichuan.py", line 611, in from_pretrained
    raise ImportError(f"Needs import model weight init func to run quantize.")
  File "D:\1-github\Baichuan2\cli_demo.py", line 13, in init_model
    model = AutoModelForCausalLM.from_pretrained(
  File "D:\1-github\Baichuan2\cli_demo.py", line 47, in main
    model, tokenizer = init_model()
  File "D:\1-github\Baichuan2\cli_demo.py", line 86, in <module>
    main()
ImportError: Needs import model weight init func to run quantize.

**Comment by WillLiGitHub** [comment]
you should install package:scipy

**Comment by before31** [comment]
1、如果依赖scipy，那为什么它没有出现在requirements.txt里面？
2、安装scipy以后仍然报错：
启动的时候控制台输出如下：
```
init model ...
Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.
E:\condaenvs\baichuan2\lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
```
然后可以启动成功，在我输入问题并回车以后，报错：
```
Exception has occurred: AttributeError
'NoneType' object has no attribute 'cdequantize_blockwise_cpu_fp32'
  File "C:\Users\WX\.cache\huggingface\modules\transformers_modules\Baichuan2-13B-Chat-4bits\modeling_baichuan.py", line 147, in forward
    proj = self.W_pack(hidden_states)
  File "C:\Users\WX\.cache\huggingface\modules\transformers_modules\Baichuan2-13B-Chat-4bits\modeling_baichuan.py", line 244, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "C:\Users\WX\.cache\huggingface\modules\transformers_modules\Baichuan2-13B-Chat-4bits\modeling_baichuan.py", line 467, in forward
    layer_outputs = decoder_layer(
  File "C:\Users\WX\.cache\huggingface\modules\transformers_modules\Baichuan2-13B-Chat-4bits\modeling_baichuan.py", line 691, in forward
    outputs = self.model(
AttributeError: 'NoneType' object has no attribute 'cdequantize_blockwise_cpu_fp32'
```

**Comment by jameswu2014** [comment]
看上去像是你用cpu推理了，如果用cpu推理就不要用4bit模型，直接float32推理。

**Comment by before31** [comment]
感谢 @jameswu2014 
如何确定我用的是CPU还是GPU呢？device_map="auto"是使用所有的GPU吗？

**Comment by eruca** [comment]
最后一句是这个啊：
ImportError: Needs import model weight init func to run quantize.

**Comment by WingsLong** [comment]
升级一下bitsandbytes到0.41.1就可以了，上面还有报错的，0.37没有Param4bit

**Comment by pbjacob** [comment]
请问解决了么？我遇到了相同的问题。

**Comment by hooplau** [comment]
解决了吗？我也遇到一样的问题，提示 AttributeError: 'NoneType' object has no attribute 'cdequantize_blockwise_cpu_fp32'

**Comment by before31** [comment]
我使用未量化的模型跑成功了，说一下我遇到的问题：
首先感谢 @WillLiGitHub ，我用你提供的代码来测试发现确实是没有cuda环境，进一步 debug 了 pytorch 代码，发现 pytorch 默认安装的是CPU版，于是我用 `pip3 install torch --index-url https://download.pytorch.org/whl/cu117` 安装了GPU版的torch。

然后再运行 cli_demo.py 又报了新的错误（或者说是信息吧，因为并不是python的调用栈），信息很长，就不贴出来了，主要内容就是告诉你说 bitsandbytes 没有找到 CUDA ，而提示信息里面出现了各种.so文件、还有LD_LIBRARY_PATH之类的，这显然是Linux下的提示。于是我到 bitsandbytes 的仓库里面去搜，发现 bitsandbytes 根本就不支持Windows部署，但有个issue里提到了有Windows版，在 [这里](https://github.com/TimDettmers/bitsandbytes/issues/748) ，按这里提到的安装Windows版 bitsandbytes: `pip install bitsandbytes-windows` ，安装完成以后，再次运行cli_demo.py就成功了。

**注意，上面是针对未量化的模型的情况。由于Windows版的 bitsandbytes 版本最高只到 0.37.5 ，因此，按 @WingsLong 提到的，是不支持 Param4bit 的，因此用这个方案跑量化过的模型仍然是行不通的，我尝试了一下也确实如此，还是老实换Linux吧。**

**Comment by before31** [comment]
我使用未量化的模型跑成功了，说一下我遇到的问题：
首先感谢 @WillLiGitHub ，我用你提供的代码来测试发现确实是没有cuda环境，进一步 debug 了 pytorch 代码，发现 pytorch 默认安装的是CPU版，于是我用 `pip3 install torch --index-url https://download.pytorch.org/whl/cu117` 安装了GPU版的torch。

然后再运行 cli_demo.py 又报了新的错误（或者说是信息吧，因为并不是python的调用栈），信息很长，就不贴出来了，主要内容就是告诉你说 bitsandbytes 没有找到 CUDA ，而提示信息里面出现了各种.so文件、还有LD_LIBRARY_PATH之类的，这显然是Linux下的提示。于是我到 bitsandbytes 的仓库里面去搜，发现 bitsandbytes 根本就不支持Windows部署，但有个issue里提到了有Windows版，在 [这里](https://github.com/TimDettmers/bitsandbytes/issues/748) ，按这里提到的安装Windows版 bitsandbytes: `pip install bitsandbytes-windows` ，安装完成以后，再次运行cli_demo.py就成功了。

**注意，上面是针对未量化的模型的情况。由于Windows版的 bitsandbytes 版本最高只到 0.37.5 ，因此，按 @WingsLong 提到的，是不支持 Param4bit 的，因此用这个方案跑量化过的模型仍然是行不通的，我尝试了一下也确实如此，还是老实换Linux吧。**

**Comment by pbjacob** [comment]
windows是下是有bitsandbytes 0.41.1的
https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl
我的conda环境里就安装的就是这个，但还是报相同的错误

**Comment by binggandata** [comment]
> windows是下是有bitsandbytes 0.41.1的 https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl 我的conda环境里就安装的就是这个，但还是报相同的错误

真的可以，解决了，谢谢！

**Comment by forcemeter** [comment]
```
pip install bitsandbytes==0.41.1
pip install scipy
```

**Comment by BIT-Xu** [comment]
我也遇到这个问题了pip install bitsandbytes==0.41.1
pip install scipy，都没用

**Comment by Chuge0335** [comment]
> ```
> pip install bitsandbytes==0.41.1
> pip install scipy
> ```
It's work ! just install the bitsandbytes==0.41.1,great!

**Comment by black-pwq** [comment]
> 升级一下bitsandbytes到0.41.1就可以了，上面还有报错的，0.37没有Param4bit

实测0.43也不行。不能低也不能高
