### ISSUE TITLE
what is z_loss_weight?

### ISSUE THREAD

**Issue by AICHENaxx** [baichuan-inc/Baichuan2#350]
hi,
i found this attribute in the forward func of BaichuanForCausalLM as z_loss = self.config.z_loss_weight * softmax_normalizer.mean(). however, there is no definition of this attribute in the config. 
my question is how to define this attribute?

**Comment by baichuan-assistant** [comment]
Please refer to this thread: https://github.com/baichuan-inc/Baichuan2/issues/325
