### ISSUE TITLE
什么时候提供更大长度的模型，和支持agents的模型啊？

### ISSUE THREAD

**Issue by ljwps** [baichuan-inc/Baichuan2#352]
1、目前对于大文本prompt有点担心
2、目前agents还挺热，希望可以加入tools这块内容

**Comment by baichuan-assistant** [comment]
开源里面，Baichuan2-13B的新版是支持到8k的：https://huggingface.co/baichuan-inc/Baichuan2-13B-Chat/tree/v2.0
闭源版本，Baichuan-Turbo有192k的版本：https://platform.baichuan-ai.com/

agent这块暂时还没有推出，可以等一等
