### ISSUE TITLE
为什么oom

### ISSUE THREAD

**Issue by qihangf** [baichuan-inc/Baichuan2#36]
https://github.com/baichuan-inc/Baichuan2#%E9%87%8F%E5%8C%96%E6%95%88%E6%9E%9C       ，你这里不是写的fp16只用26吗，为什么我v100-32G，betch-size1都oom，难道另有玄只因

**Comment by Gzj369** [comment]
楼主，你是要微调吗，上面说的26G只是推理需要的显存大小，非微调训练需要的
![image](https://github.com/baichuan-inc/Baichuan2/assets/13391430/980227fd-c251-4902-83a6-098df7ea50a9)

**Comment by qihangf** [comment]
> 楼主，你是要微调吗，上面说的26G只是推理需要的显存大小，非微调训练需要的 [hiyouga/LLaMA-Efficient-Tuning#429](https://github.com/hiyouga/LLaMA-Efficient-Tuning/issues/429)
> 
> ![image](https://user-images.githubusercontent.com/13391430/266252203-980227fd-c251-4902-83a6-098df7ea50a9.png)

哎，之前的baichuan1的13b还能用betchsize 2来跑，现在直接没得跑
