### ISSUE TITLE
不提交上次回话，同一句话问多次，有可能出现不同的结果，是啥原因，配置错了吗？

### ISSUE THREAD

**Issue by zbsean** [baichuan-inc/Baichuan2#365]
不提交上次回话，同一句话问多次，有可能出现不同的结果，是啥原因，配置错了吗？
以下是配置代码
      self.model = AutoModelForCausalLM.from_pretrained(
            "baichuan-inc/Baichuan2-13B-Chat-4bits",
            revision="v2.0",
            device_map="auto",
            trust_remote_code=True
        )
        self.model.generation_config = GenerationConfig.from_pretrained(
            "baichuan-inc/Baichuan2-13B-Chat-4bits",
            revision="v2.0",
        )
        self.tokenizer = AutoTokenizer.from_pretrained(
            "baichuan-inc/Baichuan2-13B-Chat-4bits",
            revision="v2.0",
            use_fast=False,
            trust_remote_code=True
        )

**Comment by baichuan-assistant** [comment]
模型本身回答就是随机的，可以在config里调节temperature来控制回答的多样性
