### ISSUE TITLE
streamlit到底用什么版本啊？ st.session_state has no attribute "messages"

### ISSUE THREAD

**Issue by qianma819** [baichuan-inc/Baichuan2#369]
这个到底用什么版本？从1.23.0一直尝试到了1.29.0，还是一直报错：st.session_state has no attribute "messages"

**Comment by lx0126z** [comment]
不能 python /path/to/file.py 运行， 要streamlit run /path/to/file.py

**Comment by qianma819** [comment]
> 不能 python /path/to/file.py 运行， 要streamlit run /path/to/file.py

感谢回答。已经好了，调试的时候忘记了用streamlit命令，泪崩
