### ISSUE TITLE
一个垃圾，瞎吹牛逼不说，连个维护的鸟人也没有

### ISSUE THREAD

**Issue by qianma819** [baichuan-inc/Baichuan2#371]
一个垃圾模型，吹牛逼，跑起来实际测试，屎一样的效果。吹翻译功能比GPT3.5强，结果呢？连个打ち上げ 都翻译成启动会议。お疲れさまでした，一个多么通用的句子，竟然翻译成感谢大家的参与。你烂就烂，还碰瓷GPT，不要脸

**Comment by baichuan-assistant** [comment]
首先请和气讨论 :-)

翻译肯定是有bad case的，得分也只是一个统计学意义上的事情，如果有质疑的话可以看一下评测框架和评测方式，毕竟评测框架也不是百川自己做的。

最后，可以访问https://www.baichuan-ai.com/获得最佳的模型体验。

**Comment by qianma819** [comment]
> 首先请和气讨论 :-)
> 
> 翻译肯定是有bad case的，得分也只是一个统计学意义上的事情，如果有质疑的话可以看一下评测框架和评测方式，毕竟评测框架也不是百川自己做的。
> 
> 最后，可以访问[https://www.baichuan-ai.com/获得最佳的模型体验。](https://www.baichuan-ai.com/%E8%8E%B7%E5%BE%97%E6%9C%80%E4%BD%B3%E7%9A%84%E6%A8%A1%E5%9E%8B%E4%BD%93%E9%AA%8C%E3%80%82)

放你的狗屁，八百年不出来一下，死出来干啥？

**Comment by baichuan-assistant** [comment]
<img width="769" alt="image" src="https://github.com/baichuan-inc/Baichuan2/assets/139942740/61370c05-4818-4026-9647-75f89c7c6e70">

可以去官网（[https://www.baichuan-ai.com/](https://www.baichuan-ai.com/%E8%8E%B7%E5%BE%97%E6%9C%80%E4%BD%B3%E7%9A%84%E6%A8%A1%E5%9E%8B%E4%BD%93%E9%AA%8C%E3%80%82)）体验我们最新版模型 :)
