### ISSUE TITLE
使用fastgpt框架对接baichuan2需要流式接口，请求支持

### ISSUE THREAD

**Issue by hhtao** [baichuan-inc/Baichuan2#398]
# Check if streaming is enabled
        if is_streaming:#这里暂时只支持非流式输出
            return jsonify({"error": "Streaming is not supported."}), 400

![image](https://github.com/baichuan-inc/Baichuan2/assets/9322608/fa1a9d68-fd87-428f-bbe4-9d5562aee528)
![image](https://github.com/baichuan-inc/Baichuan2/assets/9322608/ed136fd8-d310-49a1-a03c-9df3eadc4bcc)

**Comment by hhtao** [comment]
折腾了几天，我自己找到解决方案了
安装vLLm
pip install vllm
然后直接执行
python -m vllm.entrypoints.openai.api_server --served-model-name Baichuan2-7B-Chat --model /mnt/part1/models/Baichuan2-7B-Chat --max-model-len 4096 --device cuda --trust-remote-code

**Comment by xiaoToby** [comment]
> 折腾了几天，我自己找到解决方案了 安装vLLm pip install vllm 然后直接执行 python -m vllm.entrypoints.openai.api_server --served-model-name Baichuan2-7B-Chat --model /mnt/part1/models/Baichuan2-7B-Chat --max-model-len 4096 --device cuda --trust-remote-code

用这种方式启模型，就能在fastgpt中使用了吗

**Comment by xiaoToby** [comment]
> > 折腾了几天，我自己找到解决方案了 安装vLLm pip install vllm 然后直接执行 python -m vllm.entrypoints.openai.api_server --served-model-name Baichuan2-7B-Chat --model /mnt/part1/models/Baichuan2-7B-Chat --max-model-len 4096 --device cuda --trust-remote-code
> 
> 用这种方式启模型，就能在fastgpt中使用了吗

我测试用fastgpt中的oneapi去测试，发现了问题是
--served-model-name gpt-3.5-turbo 然后在oneapi中的渠道配置时模型名称也要是gpt-3.5-turbo
要用自己自定义的名称，会有报错，oneapi不会去找自定义名称的模型，而是会去找名称为gpt-3.5-turbo的模型

**Comment by xiaoToby** [comment]
> ```
>     # Check if streaming is enabled
>     if is_streaming:#这里暂时只支持非流式输出
>         return jsonify({"error": "Streaming is not supported."}), 400
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/9322608/320735498-fa1a9d68-fd87-428f-bbe4-9d5562aee528.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNDY1NjcsIm5iZiI6MTcxODM0NjI2NywicGF0aCI6Ii85MzIyNjA4LzMyMDczNTQ5OC1mYTFhOWQ2OC1mZDg3LTQyOGYtYmJlNC05ZDU1NjJhZWU1MjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTRUMDYyNDI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDUzOTdmNjA4M2EzYTg5NWE3MmU5YzBlNTZjZDYyOGViNjdhYzM1ZWQ2OTYwNDZmNDNmNmI2MzJmNmQxZDIxZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wkLZPDSaPdlkBbMawT6ayIsX6VlsWoZflX4LEZ22vlQ) ![image](https://private-user-images.githubusercontent.com/9322608/320735669-ed136fd8-d310-49a1-a03c-9df3eadc4bcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNDY1NjcsIm5iZiI6MTcxODM0NjI2NywicGF0aCI6Ii85MzIyNjA4LzMyMDczNTY2OS1lZDEzNmZkOC1kMzEwLTQ5YTEtYTAzYy05ZGYzZWFkYzRiY2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTRUMDYyNDI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWNlMGU2YzNmYjJjOWVmMDYzM2VlY2VkMmMzOGE4ZjQxMzllOWE1Mjc1OWViZWI3NTVlNTJlZmIyMTgzZmZkNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XONymNjYLD0JPJmwiqkdovvU0EB-RuFX4I2TN-9I9B0)

我看你也是用到了fastgpt,我得到的效果如下：
![image](https://github.com/baichuan-inc/Baichuan2/assets/40045458/71119150-be1f-487a-8e1b-1901993d2652)
你是不是也是这样的输出效果。。。。。
