### ISSUE TITLE
咨询商业授权问题

### ISSUE THREAD

**Issue by yiyinianhua** [baichuan-inc/Baichuan2#41]
我们是一家金融公司，我看申请商业授权里面要求法人的身份证复印件+营业执照，这个有什么替代方法么，公司的法人是董事长，目前比较困难，之前发了邮件，没有收到回复，所以就在这里询问~~

**Comment by baichuan-assistant** [comment]
直接填写发送即可，我们这里会酌情考虑哈

**Comment by liwenju0** [comment]
请问授权是永久授权吗

**Comment by baichuan-assistant** [comment]
是的
