### ISSUE TITLE
OOM问题

### ISSUE THREAD

**Issue by yaorong1996** [baichuan-inc/Baichuan2#43]
同样的推理代码。我把llama2-7b-chat的checkpoint换成了baichuan2-7b-chat。就提示显存不够了，是否有什么魔法

**Comment by jameswu2014** [comment]
你如果是16GB的显存，有可能

**Comment by yaorong1996** [comment]
> 你如果是16GB的显存，有可能

我是24G的显存，依然报OOM的错误诶
