### ISSUE TITLE
账号封禁问题

### ISSUE THREAD

**Issue by GDUTT1** [baichuan-inc/Baichuan2#46]
![1](https://github.com/baichuan-inc/Baichuan2/assets/42698795/6a136847-4937-4684-8183-3a88e94059f6)

你们百川把chat的体验页面开放出来，我除了想了解你们基本能力肯定还要看你们模型的安全性，我昨天给你们测试安全性(可能有涉及政治敏感问题)，你们就把我封了？这是几个意思？其他模型包括文心一言，智谱清言，360智脑，讯飞星火等，我都会测试他们的安全性，从来没遇到像你们这样处理用户的！！！

**Comment by YJY1117** [comment]
对啊，开放测试不就是让人进行多方面测试的吗，没有非法使用、非法宣传、非法盈利我觉得无伤大雅吧

**Comment by benywon** [comment]
感谢您的反馈，我们后续会优化这部分安全封禁的措施。

**Comment by sducxh** [comment]
刚内测时我也测过很多敏感话题，很难绕开，都是被强制中断，目前帐号ok
