### ISSUE TITLE
预训练

### ISSUE THREAD

**Issue by wanghao-007** [baichuan-inc/Baichuan2#47]
大佬好，想问一下，baichuan2基于文本的预训练代码有吗？会开放吗？想在做IFT之前做一下预训练。

**Comment by daxia-daxia** [comment]
Pretrain code sample can found here https://github.com/baichuan-inc/Baichuan-7B.

**Comment by wanghao-007** [comment]
> 

https://github.com/baichuan-inc/Baichuan-7B/blob/main/train.py 这个吗？

**Comment by mmmans** [comment]
> > 
> 
> https://github.com/baichuan-inc/Baichuan-7B/blob/main/train.py 这个吗？

Yes, but it is just an example code. You should modify for your need.

**Comment by wanghao-007** [comment]
> > > 
> > 
> > 
> > https://github.com/baichuan-inc/Baichuan-7B/blob/main/train.py 这个吗？
> 
> Yes, but it is just an example code. You should modify for your need.

似乎只能从头开始训练吗？我看直接加载config文件

**Comment by Gzj369** [comment]
可以采用LLaMA-Efficient-Tuning来预训练+微调baichuan2大模型，具体可见  https://github.com/hiyouga/LLaMA-Efficient-Tuning
