### ISSUE TITLE
模型权重数据类型为bfloat16，推理使用float16？

### ISSUE THREAD

**Issue by jet-yangqs** [baichuan-inc/Baichuan2#50]
看到https://huggingface.co/baichuan-inc/Baichuan2-13B-Chat/blob/670d17ee403f45334f53121d72feff623cc37de1/config.json#L24
权重文件是bfloat16，这里
https://github.com/baichuan-inc/Baichuan2/blob/93543b91f630367de3a5d3da6eb67551328b5fd1/cli_demo.py#L15
为什么设置为float16呢？

**Comment by jameswu2014** [comment]
都行的，你可以改成bfloat16。这么写的一个原因是考虑有些卡不支持bfloat16。

**Comment by shesung** [comment]
float16和bfloat16的准确率一样吗？

**Comment by mmmans** [comment]
> float16和bfloat16的准确率一样吗？

Yes, almost same.
