### ISSUE TITLE
小白请问各位大佬，想请问一下 base模型和chat模型的区别是什么

### ISSUE THREAD

**Issue by QJShan** [baichuan-inc/Baichuan2#54]

**Comment by wangleihitcs** [comment]
base模型是在大规模语料上以LM这种形式的预训练任务（预测下一个token）训练得来的；chat模型是在base模型上sft+rlhf上微调得来的。base模型已经有很强大的能力了，但是需要tuning即sft+强化学习rlhf后得到chat模型，对齐了人类的自然语言解锁base模型的强大能力。简而言之，base模型很强但是听不懂人话，需要用少量的tuning数据来让它听懂人话，进而和人类对话。
