### ISSUE TITLE
bugreport: need to add "tokenizer_class": "BaichuanTokenizer" to model config

### ISSUE THREAD

**Issue by Yangqing** [baichuan-inc/Baichuan2#60]
In the first place, thanks for creating and open sourcing the model!

# Symptom 

While @bddppq and I were looking into running the model with a standard huggingface `pipeline`, we found a minor bug that prevents it from loading the model. Specifically, if you directly create a pipeline, for example using code like
```
pipeline = pipeline(task=task, model=model, revision=revision, **kwargs)
```
it will produce a pipeline, but when you run it, it tells you that it encountered a `None` object - if you look deeper, the tokenizer is missing.

Note that the tutorial code (using AutoModel and AutoTokenizer) is correct, but ideally, one would want to just use a single-line `pipeline` to load the model.

# Diagnosis
Basically, when loading a pipeline and the underlying model, huggingface uses the following strategy to determine the tokenizer:

- It checks if the model type is in the `TOKENIZER_MAPPING` class, which is basically a manually maintained list here: https://github.com/huggingface/transformers/blob/fb7d246951d5f60aa36a7958841dfea72f51fc6b/src/transformers/models/auto/tokenization_auto.py#L403
  - the map is further defined here https://github.com/huggingface/transformers/blob/fb7d246951d5f60aa36a7958841dfea72f51fc6b/src/transformers/models/auto/configuration_auto.py#L30
  - and here https://github.com/huggingface/transformers/blob/fb7d246951d5f60aa36a7958841dfea72f51fc6b/src/transformers/models/auto/tokenization_auto.py#L53 
  - Basically, this is a manually maintained list that hard-codes what tokenizer should be used by what model type.

- If the above does not exist, It checks if the model's `config.json` has a `tokenizer_class` field. See https://github.com/huggingface/transformers/blob/fb7d246951d5f60aa36a7958841dfea72f51fc6b/src/transformers/pipelines/__init__.py#L836 .

Right now, Baichuan does not have a `TOKENIZER_MAPPING` manually committed to the `transformers` code repo, and the model `config.json` does not have the tokenizer_class defined. As a result, when loading the model via the pipeline interface, the tokenizer is simply not loaded.

## What to do

Of course, one way is to basically manually send a pull request to huggingface/transformers and update the TOKENIZER_MAPPING. This comes with two shortcomings, though:
- existing transformer users have to wait for transformer to push a new version, update to the new version, and then use it.
- Every new model release from Baichuan, if comes with model type changes, need to repeat the above process.

Thus, it is actually easier to simply add one line to the model `config.json` (https://huggingface.co/baichuan-inc/Baichuan2-7B-Chat/blob/main/config.json) file as follows:
```
"tokenizer_class": "BaichuanTokenizer",
``` 
and everything will be all good.

Why do we care about this - as part of our work, we are automating the process of launching LLM models, and we would love to see Baichuan being used in a much smoother way via hf pipeline instead of having to explicitly write the python code - thanks so much for looking into it!

**Comment by benywon** [comment]
We appreciate your indication of this bug, will fix it soon. Hope to hear your good news.

**Comment by Yangqing** [comment]
Confirming that it works with the newest commit https://huggingface.co/baichuan-inc/Baichuan2-7B-Chat/commit/86ffd6cb5cda3a4ff85787adb5d62ea3ed17babe .
