### ISSUE TITLE
huggingface被墙无法访问，请问是否有添加在国内可访问的模型权重文件的计划？

### ISSUE THREAD

**Issue by YananSunn** [baichuan-inc/Baichuan2#76]
如题，不知道什么时候huggingface才能恢复，希望能提供一种备选模型权重下载路径，以支持国内访问...

**Comment by QJShan** [comment]
你也是在hugging face上手动下载模型受阻，速度突然降为0吗

**Comment by YananSunn** [comment]
> 你也是在hugging face上手动下载模型受阻，速度突然降为0吗

我是直接无法访问orz，但我没有科学上网，模型太大了挂vpn下太奢侈了...

**Comment by bc-gpd** [comment]
#77

**Comment by CaoYuanPan** [comment]
我这直接是网站进不去了啊！好久没进去了，刚刚才知道huggingface被封了

**Comment by kangmuyan** [comment]
除了 挂梯，还有别的方法吗，最近刚好开始学模型，没想到这么好的网站被封了

**Comment by Monica-Han** [comment]
无语住了……找完工作回来写毕业论文，发现自己之前的代码都没法跑了，我不理解，这网站有啥问题

**Comment by DavisElppa** [comment]
可以看看这个知乎回答  https://zhuanlan.zhihu.com/p/676420788
