### ISSUE TITLE
hugging face上模型下载受阻  

### ISSUE THREAD

**Issue by QJShan** [baichuan-inc/Baichuan2#78]
![image](https://github.com/baichuan-inc/Baichuan2/assets/131762142/c1a2e207-2efa-42e9-8556-c075671eecca)
在hugging face上手动下载模型，下载几十兆后突然速度就降为零一直下载不下载，请问有大佬知道是什么原因吗。
我换了电脑和账号进行尝试，还是一样的情况。

**Comment by bc-gpd** [comment]
可以查看这个issue，通过国内渠道下载，模型文件是一样的 #77
