### ISSUE TITLE
huggingface不能访问了

### ISSUE THREAD

**Issue by liaoweiguo** [baichuan-inc/Baichuan2#88]

**Comment by liaoweiguo** [comment]
现在在哪里下载/更新模型？

**Comment by QJShan** [comment]
前往达摩院的模型库下载 modelscope

**Comment by sun1092469590** [comment]
> 前往达摩院的模型库下载 modelscope

modelscope里面的好像还是上周的旧模型，baichuan2是更新了新模型？

**Comment by QJShan** [comment]
按照模型上传时间来看是相隔的几天，期间模型参数是否有更新变化就不清楚了

**Comment by baichuan-assistant** [comment]
> > 前往达摩院的模型库下载 modelscope
> 
> modelscope里面的好像还是上周的旧模型，baichuan2是更新了新模型？

有最新的Baichuan 2的模型的噢

**Comment by sun1092469590** [comment]
> > > 前往达摩院的模型库下载 modelscope
> > 
> > 
> > modelscope里面的好像还是上周的旧模型，baichuan2是更新了新模型？
> 
> 有最新的Baichuan 2的模型的噢

@baichuan-assistant  好的好的，请问下有没有其他下载路径呢？huggingface今天翻墙也进不去。。。

**Comment by baichuan-assistant** [comment]
> > > > 前往达摩院的模型库下载 modelscope
> > > 
> > > 
> > > modelscope里面的好像还是上周的旧模型，baichuan2是更新了新模型？
> > 
> > 
> > 有最新的Baichuan 2的模型的噢
> 
> @baichuan-assistant 好的好的，请问下有没有其他下载路径呢？huggingface今天翻墙也进不去。。。

wisemodel也有的哈

**Comment by sun1092469590** [comment]
> > > > > 前往达摩院的模型库下载 modelscope
> > > > 
> > > > 
> > > > modelscope里面的好像还是上周的旧模型，baichuan2是更新了新模型？
> > > 
> > > 
> > > 有最新的Baichuan 2的模型的噢
> > 
> > 
> > @baichuan-assistant 好的好的，请问下有没有其他下载路径呢？huggingface今天翻墙也进不去。。。
> 
> wisemodel也有的哈

好的好的，感谢快速回复，我看看哈

**Comment by liaoweiguo** [comment]
魔塔支持git下载吗，我看文档有，git clone或者git lfs clone都失败

**Comment by QJShan** [comment]
> > > > > 前往达摩院的模型库下载 modelscope
> > > > 
> > > > 
> > > > modelscope里面的好像还是上周的旧模型，baichuan2是更新了新模型？
> > > 
> > > 
> > > 有最新的Baichuan 2的模型的噢
> > 
> > 
> > @baichuan-assistant 好的好的，请问下有没有其他下载路径呢？huggingface今天翻墙也进不去。。。
> 
> wisemodel也有的哈

我刚尝试在wisemodel上下载，为何点击下载后只有几K。好像不可用。

**Comment by byrain** [comment]
> > > > > > 前往达摩院的模型库下载 modelscope
> > > > > 
> > > > > 
> > > > > modelscope里面的好像还是上周的旧模型，baichuan2是更新了新模型？
> > > > 
> > > > 
> > > > 有最新的Baichuan 2的模型的噢
> > > 
> > > 
> > > @baichuan-assistant 好的好的，请问下有没有其他下载路径呢？huggingface今天翻墙也进不去。。。
> > 
> > 
> > wisemodel也有的哈
> 
> 我刚尝试在wisemodel上下载，为何点击下载后只有几K。好像不可用。

+1
