### ISSUE TITLE
OSError: Unable to load weights from pytorch checkpoint file for '/opt/llm_models/Baichuan2-13b/pytorch_model-00002-of-00003.bin' at '/opt/llm_models/Baichuan2-13b/pytorch_model-00002-of-00003.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please s et from_tf=True.

### ISSUE THREAD

**Issue by shujun1992** [baichuan-inc/Baichuan2#96]
OSError: Unable to load weights from pytorch checkpoint file for '/opt/llm_models/Baichuan2-13b/pytorch_model-00002-of-00003.bin' at '/opt/llm_models/Baichuan2-13b/pytorch_model-00002-of-00003.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please s
et from_tf=True.

**Comment by jameswu2014** [comment]
是不是模型文件有问题

**Comment by shujun1992** [comment]
Baichuan2-13b bin1  和bin2 一个

**Comment by MrRace** [comment]
看样子是微调的时候，直接用HF上的模型文件进行初始化导致的

**Comment by KyrieXu11** [comment]
这个请问解决了吗？如果解决的话咋解决的？

**Comment by shaunxiong** [comment]
请问这个问题解决了吗，应该如何解决这个问题呀

**Comment by yuque01** [comment]
> 请问这个问题解决了吗，应该如何解决这个问题呀

应该是模型文件的问题，对比下载的模型和huggingface上的模型大小是否一致，不一致的话重新下载一下最新的
