### ISSUE TITLE
关于4bits微调

### ISSUE THREAD

**Issue by MurraryZhao** [baichuan-inc/Baichuan2#99]
你好，在fine-tune 4bits模型时报错：                                                                                                                                                      
ValueError: The model you want to train is loaded in 8-bit precision.  if you want to fine-tune an 8-bit model, please make sure that you have installed `bitsandbytes>=0.37.0`.
但是确实已经安装了0.41.1版本的bitsandbytes。
看代码发现是transformers/trainer.py中line402，model没有_is_quantized_training_enabled。
我简单粗暴的在Beichuan2-7B-Chat-4bits/modeling_baichuan.py文件的line611加了一行model._is_quantized_training_enabled = True

可以正常finetuing了。大佬们能不能看下这样合理嘛。。。

@bc-gpd 

修改后modeling_baichuan.py代码line611：
`
            model.is_quantized = True
            model._is_quantized_training_enabled = True
            device_map = kwargs.pop("device_map", None)
`

**Comment by piwawa** [comment]
> 你好，在fine-tune 4bits模型时报错： ValueError: The model you want to train is loaded in 8-bit precision. if you want to fine-tune an 8-bit model, please make sure that you have installed `bitsandbytes>=0.37.0`. 但是确实已经安装了0.41.1版本的bitsandbytes。 看代码发现是transformers/trainer.py中line402，model没有_is_quantized_training_enabled。 我简单粗暴的在Beichuan2-7B-Chat-4bits/modeling_baichuan.py文件的line611加了一行model._is_quantized_training_enabled = True
> 
> 可以正常finetuing了。大佬们能不能看下这样合理嘛。。。
> 
> @bc-gpd
> 
> 修改后modeling_baichuan.py代码line611： `model.is_quantized = True model._is_quantized_training_enabled = True device_map = kwargs.pop("device_map", None)`

后来微调正常吗？

**Comment by MurraryZhao** [comment]
> [piwawa](/piwawa)
后来微调的7B-Base

**Comment by piwawa** [comment]
> > [piwawa](/piwawa)
> > 后来微调的7B-Base

4bit微调最后还是有问题吗？我自己微调4bit好像不能用lora，但是不用 lora有时候也有奇奇怪怪的错误

**Comment by MurraryZhao** [comment]
> > > [piwawa](/piwawa)
> > > 后来微调的7B-Base
> 
> 4bit微调最后还是有问题吗？我自己微调4bit好像不能用lora，但是不用 lora有时候也有奇奇怪怪的错误

最后还是没成功
之前有人说4bits不能微调https://github.com/baichuan-inc/Baichuan2/issues/64#issuecomment-1728459719

**Comment by TanateT** [comment]
> > > > [piwawa](/piwawa)
> > > > 后来微调的7B-Base
> > 
> > 
> > 4bit微调最后还是有问题吗？我自己微调4bit好像不能用lora，但是不用 lora有时候也有奇奇怪怪的错误
> 
> 最后还是没成功 之前有人说4bits不能微调[#64 (comment)](https://github.com/baichuan-inc/Baichuan2/issues/64#issuecomment-1728459719)

你好，最后生成的模型是adapter_model.safetensors不是adapter_model.safetensors.bin的格式这是什么原因，您知道么

**Comment by MurraryZhao** [comment]
> > > > > [piwawa](/piwawa)
> > > > > 后来微调的7B-Base
> > > 
> > > 
> > > 4bit微调最后还是有问题吗？我自己微调4bit好像不能用lora，但是不用 lora有时候也有奇奇怪怪的错误
> > 
> > 
> > 最后还是没成功 之前有人说4bits不能微调[#64 (comment)](https://github.com/baichuan-inc/Baichuan2/issues/64#issuecomment-1728459719)
> 
> 你好，最后生成的模型是adapter_model.safetensors不是adapter_model.safetensors.bin的格式这是什么原因，您知道么

这个不清楚
